apiVersion: v1
kind: Secret
metadata:
  name: ror-stay-secrets
  namespace: ror-stay
type: Opaque
stringData:
  jwt-secret: "6ee103fe9864c5448deafb62b50c698944053dbcfb0f9a661ec3eec407f2f476"
  admin-password-hash: "$2b$12$oE4Gu8SfRtqmSmasfXBLO.na/3p3zuvJgFGreCve62xZP8aaJsvFS"
  mongo-url: "mongodb://mongodb-service:27017"
  db-name: "ror_stay"
