apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: ror-stay
  annotations:
    # For AWS: service.beta.kubernetes.io/aws-load-balancer-type: nlb
    # For Azure: service.beta.kubernetes.io/azure-load-balancer-resource-group: your-rg
    # For GCP: cloud.google.com/load-balancer-type: External
spec:
  type: LoadBalancer  # Use NodePort for local testing, LoadBalancer for cloud
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    name: http
    # For NodePort: nodePort: 30080
